WORKING DIRECTORY:  /Users/fjolnirthrastarson/Documents/Fintech HR/Annall_Lightweight_Blockchain.nosync
MAIN STARTED
[ID] 1  [ROUNDS] 0
::> Starting up Blockchain DB = using  /Users/fjolnirthrastarson/Documents/Fintech HR/Annall_Lightweight_Blockchain.nosync/src/test_node_1/blockchain.db
DB: Local Blockchain ready for use
Local block chain database successfully initialized
::> Starting up peer-to-peer network engine with id  1
[IS WRITER] node with id: 1 is a writer: True
Listening on port: 15000
Peer-to-peer network engine up  and running as: P2P : Protocol communication
THE ID:  1
TCP PORT: 5001
::> Starting up ClientServer thread
Server started - listening at 127.0.0.1 : 5001
ClientServer up and running as: TCPServerThread
::> Starting up BlockChainEngine
Protocol Engine up and running as: ProtocolEngine
Traceback (most recent call last):
  File "./src/main.py", line 107, in <module>
    PEthread.join() # MainThread awaits here for cleanup
  File "/Users/fjolnirthrastarson/opt/anaconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/fjolnirthrastarson/opt/anaconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/Users/fjolnirthrastarson/opt/anaconda3/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/Users/fjolnirthrastarson/opt/anaconda3/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
